function [displacement, arr] = FindMatch(landscape, ... 
    object, positionX, positionY, searchRangeX, searchRangeY)
    [m, n] = size(object); 
    arr    = zeros(m + 1, n + 1);
    for II = 0:searchRangeX
        for JJ = 0:searchRangeY
            absoluteDiff = abs(... 
                landscape(... 
                    positionX + II: positionX + m + II, ...
                    positionY + JJ: positionY + n + JJ, ...
                    :) ...
                - object);
            arr(II + 1, JJ + 1) = sum(absoluteDiff, "all");
        end
    end
    [~, displacement] = min(arr);
end